flowchart TD
  app["Open App"]
  budgetList["List Budgets"]
  budgetSync["Sync Budget"]
  info["About"]
  licenses["Licenses"]
  login["Login"]
  manageStorage["Manage Storage"]
  password["Change Password"]
  settings["Settings"]
  scheduleSettings["Schedule Settings"]
  transactionSettings["Transaction Settings"]
  systemUiSettings["System UI Settings"]
  formatSettings["Format Settings"]
  currencySettings["Currency Settings"]
  themeSettings["Theme Settings"]
  customThemes["Custom Themes"]
  inspectTheme["Inspect Theme"]
  searchTheme["Search Theme"]
  url["Server URL"]

  subgraph budgetNavRail["Budget Nav Rail"]
    home["Home"]
    budget["Budget"]
    transactions["Transactions"]
    accountTransactions["Account Transactions"]
    tagTransactions["Tag Transactions"]
    uncategorisedTransactions["Uncategorised Transactions"]
    reportsDashboard["Reports Dashboard"]
    report["Report"]
    createReport["Create Report"]
    searchReports["Search Reports"]
    listTags["List Tags"]
    createTag["Create Tag"]
    editTag["Edit Tag"]
    searchTags["Search Tags"]
    listSchedules["List Schedules"]
    editSchedule["Edit Schedule"]
    searchSchedules["Search Schedules"]
    bankSync["Bank Sync"]
    bankSyncSettings["Bank Sync Settings"]
    linkBankAccount["Link Bank Account"]
    bankSyncProviders["Bank Sync Providers"]
    bankSyncProviderSetup["Bank Sync Provider Setup"]
  end

  app --valid token--> budgetList
  app --"valid token + last opened budget with local files"--> budgetNavRail
  app --no token--> login
  app --no token, no url--> url

  budgetList --tap budget - unsynced--> budgetSync
  budgetList --tap budget - synced--> budgetNavRail
  budgetList --tap change password--> password
  budgetList --tap settings--> settings
  budgetList --tap change url--> url
  budgetList --tap about--> info

  settings --tap schedules--> scheduleSettings
  settings --tap theme--> themeSettings
  settings --tap transactions--> transactionSettings
  settings --tap system UI--> systemUiSettings
  settings --tap formatting--> formatSettings
  settings --tap currency--> currencySettings
  themeSettings --tap custom themes--> customThemes
  themeSettings --tap inspect--> inspectTheme
  customThemes --tap inspect--> inspectTheme
  inspectTheme --tap search--> searchTheme

  budgetSync --budget synced--> budgetNavRail

  info --tap licenses--> licenses
  info --tap manage storage--> manageStorage

  login --valid token--> budgetList
  login --tap about--> info
  login --tap change url--> url

  url --tap try demo--> budgetNavRail

  budgetNavRail --back--> budgetList
  budgetNavRail --tap exit demo--> url
  budgetNavRail --tap about--> info

  home --tap account--> accountTransactions
  home --no accounts--> bankSync
  home --tap upcoming schedule--> editSchedule
  home --see all upcoming--> listSchedules

  budget --review uncategorised--> uncategorisedTransactions

  reportsDashboard --tap report--> report
  reportsDashboard --tap create--> createReport
  reportsDashboard --tap search--> searchReports
  searchReports --tap report--> report

  listTags --tap add--> createTag
  listTags --tap view transactions--> tagTransactions
  listTags --tap tag--> editTag
  listTags --tap search--> searchTags
  searchTags --tap tag--> editTag

  listSchedules --tap schedule--> editSchedule
  listSchedules --tap search--> searchSchedules
  listSchedules --tap settings--> scheduleSettings
  searchSchedules --tap schedule--> editSchedule

  bankSync --tap linked account--> bankSyncSettings
  bankSync --tap unlinked account--> linkBankAccount
  bankSync --tap add account--> linkBankAccount
  bankSync --tap providers--> bankSyncProviders
  linkBankAccount --no providers set up--> bankSyncProviders
  bankSyncProviders --tap provider--> bankSyncProviderSetup
