flowchart TD
  app["Open App"]
  budgetList["List Budgets"]
  budgetSync["Sync Budget"]
  info["About"]
  licenses["Licenses"]
  login["Login"]
  manageStorage["Manage Storage"]
  password["Change Password"]
  settings["Settings"]
  url["Server URL"]

  subgraph budgetNavRail["Budget Nav Rail"]
    transactions["Transactions"]
    reportsDashboard["Reports Dashboard"]
    report["Report"]
    createReport["Create Report"]
  end

  app --valid token--> budgetList
  app --"valid token + last opened budget with local files"--> budgetNavRail
  app --no token--> login
  app --no token, no url--> url

  budgetList --tap budget - unsynced--> budgetSync
  budgetList --tap budget - synced--> budgetNavRail
  budgetList --tap change password--> password
  budgetList --tap settings--> settings
  budgetList --tap change url--> url
  budgetList --tap about--> info

  budgetSync --budget synced--> budgetNavRail

  info --tap licenses--> licenses
  info --tap manage storage--> manageStorage

  login --valid token--> budgetList
  login --tap about--> info
  login --tap change url--> url

  budgetNavRail --back--> budgetList
  budgetNavRail --tap about--> info

  reportsDashboard --tap report--> report
  reportsDashboard --tap create--> createReport
