...@../../../atlas/classes.d2
core_model: :core:model { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
prefs -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
  }
}
