...@../../../../atlas/classes.d2
account_domain: :account:domain { class: module-Multiplatform }
api_actual: :api:actual { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
codegen_annotation: :codegen:annotation { class: module-Multiplatform }
core_model: :core:model { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
account_domain -> api_actual { class: link-implementation }
account_domain -> core_model { class: link-api }
account_domain -> logging { class: link-implementation }
account_domain -> prefs { class: link-implementation }
api_actual -> budget_model { class: link-api }
api_actual -> codegen_annotation { class: link-implementation }
api_actual -> core_model { class: link-api }
prefs -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
    module-dummy1 -> module-dummy2: api { class: link-api }
  }
}
