@file:Suppress("UnusedReceiverParameter")

package aktual.core.icons.material

import aktual.core.icons.material.internal.materialIcon
import aktual.core.icons.material.internal.materialPath
import androidx.compose.ui.graphics.vector.ImageVector

val MaterialIcons.Deselect: ImageVector by lazy {
  materialIcon(name = "Deselect") {
    materialPath {
      moveTo(3.0f, 13.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineTo(3.0f)
      verticalLineTo(13.0f)
      close()
      moveTo(7.0f, 21.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineTo(7.0f)
      verticalLineTo(21.0f)
      close()
      moveTo(1.0f, 3.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      verticalLineTo(3.0f)
      horizontalLineTo(1.0f)
      close()
      moveTo(19.0f, 3.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      verticalLineTo(3.0f)
      horizontalLineTo(19.0f)
      close()
      moveTo(3.0f, 9.0f)
      horizontalLineToRelative(2.0f)
      verticalLineTo(7.0f)
      horizontalLineTo(3.0f)
      verticalLineTo(9.0f)
      close()
      moveTo(15.0f, 5.0f)
      horizontalLineToRelative(2.0f)
      verticalLineTo(3.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineTo(5.0f)
      close()
      moveTo(7.83f, 5.0f)
      lineTo(7.0f, 4.17f)
      verticalLineTo(3.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(2.0f)
      horizontalLineTo(7.83f)
      close()
      moveTo(19.83f, 17.0f)
      lineTo(19.0f, 16.17f)
      verticalLineTo(15.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(2.0f)
      horizontalLineTo(19.83f)
      close()
      moveTo(21.19f, 21.19f)
      lineTo(2.81f, 2.81f)
      lineTo(1.39f, 4.22f)
      lineTo(4.17f, 7.0f)
      horizontalLineTo(3.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      verticalLineTo(7.83f)
      lineToRelative(2.0f, 2.0f)
      verticalLineTo(17.0f)
      horizontalLineToRelative(7.17f)
      lineToRelative(2.0f, 2.0f)
      horizontalLineTo(15.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-1.17f)
      lineToRelative(2.78f, 2.78f)
      lineTo(21.19f, 21.19f)
      close()
      moveTo(9.0f, 15.0f)
      verticalLineToRelative(-3.17f)
      lineTo(12.17f, 15.0f)
      horizontalLineTo(9.0f)
      close()
      moveTo(15.0f, 12.17f)
      verticalLineTo(9.0f)
      horizontalLineToRelative(-3.17f)
      lineToRelative(-2.0f, -2.0f)
      horizontalLineTo(17.0f)
      verticalLineToRelative(7.17f)
      lineTo(15.0f, 12.17f)
      close()
    }
  }
}
