@file:Suppress("UnusedReceiverParameter")

package aktual.core.icons.material

import aktual.core.icons.material.internal.materialIcon
import aktual.core.icons.material.internal.materialPath
import androidx.compose.ui.graphics.vector.ImageVector

val MaterialIcons.GridOn: ImageVector by lazy {
  materialIcon(name = "GridOn") {
    materialPath {
      moveTo(20.0f, 2.0f)
      lineTo(4.0f, 2.0f)
      curveToRelative(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f)
      verticalLineToRelative(16.0f)
      curveToRelative(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f)
      horizontalLineToRelative(16.0f)
      curveToRelative(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f)
      lineTo(22.0f, 4.0f)
      curveToRelative(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f)
      close()
      moveTo(8.0f, 20.0f)
      lineTo(4.0f, 20.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(8.0f, 14.0f)
      lineTo(4.0f, 14.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(8.0f, 8.0f)
      lineTo(4.0f, 8.0f)
      lineTo(4.0f, 4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(14.0f, 20.0f)
      horizontalLineToRelative(-4.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(14.0f, 14.0f)
      horizontalLineToRelative(-4.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(14.0f, 8.0f)
      horizontalLineToRelative(-4.0f)
      lineTo(10.0f, 4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(20.0f, 20.0f)
      horizontalLineToRelative(-4.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(20.0f, 14.0f)
      horizontalLineToRelative(-4.0f)
      verticalLineToRelative(-4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
      moveTo(20.0f, 8.0f)
      horizontalLineToRelative(-4.0f)
      lineTo(16.0f, 4.0f)
      horizontalLineToRelative(4.0f)
      verticalLineToRelative(4.0f)
      close()
    }
  }
}
