@file:Suppress("UnusedReceiverParameter")

package aktual.core.icons.material

import aktual.core.icons.material.internal.materialIcon
import aktual.core.icons.material.internal.materialPath
import androidx.compose.ui.graphics.vector.ImageVector

val MaterialIcons.SelectAll: ImageVector by lazy {
  materialIcon(name = "SelectAll") {
    materialPath {
      moveTo(3.0f, 5.0f)
      horizontalLineToRelative(2.0f)
      lineTo(5.0f, 3.0f)
      curveToRelative(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f)
      close()
      moveTo(3.0f, 13.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      lineTo(3.0f, 11.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(7.0f, 21.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      lineTo(7.0f, 19.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(3.0f, 9.0f)
      horizontalLineToRelative(2.0f)
      lineTo(5.0f, 7.0f)
      lineTo(3.0f, 7.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(13.0f, 3.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      lineTo(13.0f, 3.0f)
      close()
      moveTo(19.0f, 3.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      curveToRelative(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f)
      close()
      moveTo(5.0f, 21.0f)
      verticalLineToRelative(-2.0f)
      lineTo(3.0f, 19.0f)
      curveToRelative(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f)
      close()
      moveTo(3.0f, 17.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      lineTo(3.0f, 15.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(9.0f, 3.0f)
      lineTo(7.0f, 3.0f)
      verticalLineToRelative(2.0f)
      horizontalLineToRelative(2.0f)
      lineTo(9.0f, 3.0f)
      close()
      moveTo(11.0f, 21.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(19.0f, 13.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(19.0f, 21.0f)
      curveToRelative(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(19.0f, 9.0f)
      horizontalLineToRelative(2.0f)
      lineTo(21.0f, 7.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(19.0f, 17.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(15.0f, 21.0f)
      horizontalLineToRelative(2.0f)
      verticalLineToRelative(-2.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(15.0f, 5.0f)
      horizontalLineToRelative(2.0f)
      lineTo(17.0f, 3.0f)
      horizontalLineToRelative(-2.0f)
      verticalLineToRelative(2.0f)
      close()
      moveTo(7.0f, 17.0f)
      horizontalLineToRelative(10.0f)
      lineTo(17.0f, 7.0f)
      lineTo(7.0f, 7.0f)
      verticalLineToRelative(10.0f)
      close()
      moveTo(9.0f, 9.0f)
      horizontalLineToRelative(6.0f)
      verticalLineToRelative(6.0f)
      lineTo(9.0f, 15.0f)
      lineTo(9.0f, 9.0f)
      close()
    }
  }
}
