aktual.android.compileSdk=37
aktual.android.minSdk=28
aktual.android.targetSdk=37
aktual.test.disableRelease=true

kotlin.native.disableCompilerDaemon=true

metro.reportsDestination=reports/metro

org.gradle.caching=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=fail
org.gradle.configuration-cache=true
org.gradle.console=colored
org.gradle.daemon.idletimeout=3600000
org.gradle.daemon=true
org.gradle.isolated-projects=true
org.gradle.jvmargs=-Xmx4096M -XX:+UseParallelGC -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
org.gradle.welcome=never
org.gradle.workers.max=4

straitjacket.enabled=true
straitjacket.failOnViolation=true
straitjacket.logForcedVersions=INFO
