...@../../../../../atlas/classes.d2
api_actual: :api:actual { class: module-Multiplatform }
budget_data: :budget:data { class: module-Multiplatform }
budget_list_vm: :budget:list:vm { class: module-ViewModel }
budget_model: :budget:model { class: module-Multiplatform }
codegen_annotation: :codegen:annotation { class: module-Multiplatform }
core_di: :core:di { class: module-DI }
core_model: :core:model { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
api_actual -> budget_model { class: link-api }
api_actual -> codegen_annotation { class: link-implementation }
api_actual -> core_model { class: link-api }
budget_data -> budget_model { class: link-api }
budget_data -> core_model { class: link-api }
budget_data -> logging { class: link-implementation }
budget_list_vm -> api_actual { class: link-implementation }
budget_list_vm -> budget_model { class: link-api }
budget_list_vm -> core_di { class: link-api }
budget_list_vm -> core_model { class: link-api }
budget_list_vm -> logging { class: link-implementation }
budget_list_vm -> prefs { class: link-implementation }
core_di -> budget_data { class: link-api }
core_di -> budget_model { class: link-api }
prefs -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-ViewModel: ViewModel { class: module-ViewModel }
    module-DI: DI { class: module-DI }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
  }
}
