name: Report Build Results
description: Publish build report annotations

runs:
  using: composite
  steps:
    - name: Report build results
      uses: gmazzo/publish-report-annotations@8a848c2642d68a51451fec8b36f6ea173488b60d # v1
      if: ${{ !cancelled() }}
      with:
        filterPassedTests: true
        invalidFileAction: report
