name: Report Build Results
description: Publish build report annotations

runs:
  using: composite
  steps:
    - name: Report build results
      uses: gmazzo/publish-report-annotations@c76b3572e2d4588eb5abce88d5b9390dff17bf82 # v1
      if: ${{ !cancelled() }}
      with:
        filterPassedTests: true
        invalidFileAction: report
