###
# @name secret/set
POST {{ACTUAL_BASE_URL}}/secret
X-ACTUAL-TOKEN: {{ACTUAL_TOKEN}}
Content-Type: application/json

{
    "name": "simplefin_token",
    "value": "{{ACTUAL_SIMPLEFIN_TOKEN}}"
}

<> set-success.200.json

###
# @name secret/delete
DELETE {{ACTUAL_BASE_URL}}/secret/simplefin_accessKey
X-ACTUAL-TOKEN: {{ACTUAL_TOKEN}}

<> set-success.200.json
