# Configured here instead of @Config to work around a Kotlin compiler crash caused by Burst's @InterceptTest
# generating annotation implementations for @Config's Class<?> properties.
application=aktual.app.android.AktualApplication
minSdk=31
maxSdk=34
