...@../../../../atlas/classes.d2
account_domain: :account:domain { class: module-Multiplatform }
account_ui: :account:ui { class: module-UI }
account_vm: :account:vm { class: module-ViewModel }
api_actual: :api:actual { class: module-Multiplatform }
budget_data: :budget:data { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
codegen_annotation: :codegen:annotation { class: module-Multiplatform }
core_di: :core:di { class: module-DI }
core_model: :core:model { class: module-Multiplatform }
core_ui: :core:ui { class: module-UI }
l10n: :l10n { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
account_domain -> api_actual { class: link-implementation }
account_domain -> core_model { class: link-api }
account_domain -> logging { class: link-implementation }
account_domain -> prefs { class: link-implementation }
account_ui -> account_domain { class: link-implementation }
account_ui -> account_vm { class: link-api }
account_ui -> core_model { class: link-api }
account_ui -> core_ui { class: link-api }
account_ui -> l10n { class: link-implementation }
account_ui -> logging { class: link-implementation }
account_vm -> account_domain { class: link-api }
account_vm -> api_actual { class: link-implementation }
account_vm -> core_di { class: link-api }
account_vm -> core_model { class: link-api }
account_vm -> logging { class: link-implementation }
account_vm -> prefs { class: link-api }
api_actual -> budget_model { class: link-api }
api_actual -> codegen_annotation { class: link-implementation }
api_actual -> core_model { class: link-api }
budget_data -> budget_model { class: link-api }
budget_data -> core_model { class: link-api }
budget_data -> logging { class: link-implementation }
core_di -> budget_data { class: link-api }
core_di -> budget_model { class: link-api }
core_ui -> budget_model { class: link-api }
core_ui -> core_di { class: link-implementation }
core_ui -> core_model { class: link-api }
core_ui -> l10n { class: link-implementation }
prefs -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-UI: UI { class: module-UI }
    module-ViewModel: ViewModel { class: module-ViewModel }
    module-DI: DI { class: module-DI }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
    module-dummy1 -> module-dummy2: api { class: link-api }
  }
}
