...@../../../../atlas/classes.d2
api_actual: :api:actual { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
codegen_annotation: :codegen:annotation { class: module-Multiplatform }
core_model: :core:model { class: module-Multiplatform }
api_actual -> budget_model { class: link-api }
api_actual -> codegen_annotation { class: link-implementation }
api_actual -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
  }
}
