// See https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file
aktual.about.data.*
aktual.account.model.*
aktual.api.model.*
aktual.budget.model.*
androidx.navigation3.runtime.NavKey
kotlin.enums.EnumEntries
kotlin.ranges.ClosedFloatingPointRange
kotlin.time.Instant
kotlinx.datetime.DayOfWeek
kotlinx.datetime.LocalDate
kotlinx.datetime.YearMonth
kotlinx.datetime.YearMonthRange
