---
comments:
  active: false

complexity:
  CognitiveComplexMethod:
    active: false
  CyclomaticComplexMethod:
    allowedComplexity: 20
    ignoreSingleWhenExpression: true
  LabeledExpression:
    active: false
  LongMethod:
    allowedLines: 100
  LongParameterList:
    allowedConstructorParameters: 10
    allowedFunctionParameters: 10
    ignoreDefaultParameters: true
  NamedArguments:
    allowedArguments: 7
    ignoreArgumentsMatchingNames: true
  NestedScopeFunctions:
    functions: [ "kotlin.apply", "kotlin.run", "kotlin.with" ]
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    excludes: [ "**/test/**", "**/*Test/**" ]
  TooManyFunctions:
    allowedFunctionsPerClass: 20
    allowedFunctionsPerFile: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerObject: 20
    ignorePrivate: true

coroutines:
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    excludes: [ "**/test/**", "**/*Test/**" ]

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  BooleanPropertyNaming:
    active: false
  FunctionNameMaxLength:
    excludes: [ "**/test/**", "**/*Test/**" ]
    maximumFunctionNameLength: 40
  FunctionNaming:
    excludeClassPattern: ".*Test$"
    functionPattern: "[a-zA-Z][a-zA-Z0-9]*"
  # https://github.com/detekt/detekt/issues/5362
  NonBooleanPropertyPrefixedWithIs:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: false
  ImplicitUnitReturnType:
    active: false
  LateinitUsage:
    excludes: [ "**/test/**", "**/*Test/**" ]
  MissingUseCall:
    active: false
  NullableToStringCall:
    active: false
  UnnamedParameterUse:
    active: false

style:
  CascadingCallWrapping:
    active: false
  DataClassContainsFunctions:
    allowOperators: true
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  ForbiddenComment:
    active: false
  MagicNumber:
    excludes: [ "**/test/**", "**/*Test/**" ]
    ignoreAnnotated:
      - "DesktopPreview"
      - "LandscapePreview"
      - "PortraitPreview"
      - "Preview"
    ignoreCompanionObjectPropertyDeclaration: true
    ignorePropertyDeclaration: true
  MaxChainedCallsOnSameLine:
    maxChainedCalls: 8
  MaxLineLength:
    maxLineLength: 120
  MultilineRawStringIndentation:
    active: false
  OptionalUnit:
    active: false
  ReturnCount:
    max: 5
  UnderscoresInNumericLiterals:
    active: false
  UnnecessaryFullyQualifiedName:
    # caused issues with logcat.logcat
    active: false
  UnusedPrivateFunction:
    ignoreAnnotated:
      - "DesktopPreview"
      - "LandscapePreview"
      - "PortraitPreview"
      - "Preview"
      - "TabletPreview"
  UseIfInsteadOfWhen:
    ignoreWhenContainingVariableDeclaration: true
