...@../../../../atlas/classes.d2
api_actual: :api:actual { class: module-Multiplatform }
api_builder: :api:builder { class: module-Multiplatform }
budget_data: :budget:data { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
codegen_annotation: :codegen:annotation { class: module-Multiplatform }
core_model: :core:model { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
test_kotlin: :test:kotlin { class: module-Multiplatform }
api_actual -> budget_model { class: link-api }
api_actual -> codegen_annotation { class: link-implementation }
api_actual -> core_model { class: link-api }
api_builder -> core_model { class: link-api }
api_builder -> logging { class: link-implementation }
budget_data -> budget_model { class: link-api }
budget_data -> core_model { class: link-api }
budget_data -> logging { class: link-implementation }
test_kotlin -> api_actual { class: link-implementation }
test_kotlin -> api_builder { class: link-implementation }
test_kotlin -> budget_data { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
  }
}
