...@../../../../../atlas/classes.d2
budget_data: :budget:data { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
budget_transactions_ui: :budget:transactions:ui { class: module-UI }
budget_transactions_vm: :budget:transactions:vm { class: module-ViewModel }
core_di: :core:di { class: module-DI }
core_model: :core:model { class: module-Multiplatform }
core_ui: :core:ui { class: module-UI }
l10n: :l10n { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
budget_data -> budget_model { class: link-api }
budget_data -> core_model { class: link-api }
budget_data -> logging { class: link-implementation }
budget_transactions_ui -> budget_model { class: link-api }
budget_transactions_ui -> budget_transactions_vm { class: link-api }
budget_transactions_ui -> core_model { class: link-implementation }
budget_transactions_ui -> core_ui { class: link-api }
budget_transactions_ui -> l10n { class: link-implementation }
budget_transactions_vm -> budget_data { class: link-api }
budget_transactions_vm -> budget_model { class: link-api }
budget_transactions_vm -> core_di { class: link-api }
budget_transactions_vm -> core_di { class: link-implementation }
budget_transactions_vm -> core_model { class: link-implementation }
budget_transactions_vm -> logging { class: link-implementation }
budget_transactions_vm -> prefs { class: link-implementation }
core_di -> budget_data { class: link-api }
core_di -> budget_model { class: link-api }
core_ui -> budget_model { class: link-api }
core_ui -> core_di { class: link-implementation }
core_ui -> core_model { class: link-api }
core_ui -> l10n { class: link-implementation }
prefs -> core_model { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-UI: UI { class: module-UI }
    module-ViewModel: ViewModel { class: module-ViewModel }
    module-DI: DI { class: module-DI }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
  }
}
