###
# @name releases actualbudget/actual
GET https://api.github.com/repos/actualbudget/actual/releases/latest?per_page=1

<> list-releases-actual.200.json

###
# @name releases jonapoul/actual-android
GET https://api.github.com/repos/jonapoul/actual-android/releases/latest?per_page=1

<> list-releases-not-found.404.json
