...@../../../../atlas/classes.d2
core_model: :core:model { class: module-Multiplatform }
prefs: :prefs { class: module-Multiplatform }
test_android: :test:android { class: module-Android }
prefs -> core_model { class: link-api }
test_android -> prefs { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-Android: Android { class: module-Android }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
  }
}
