...@../../../../atlas/classes.d2
budget_data: :budget:data { class: module-Multiplatform }
budget_model: :budget:model { class: module-Multiplatform }
core_di: :core:di { class: module-DI }
core_model: :core:model { class: module-Multiplatform }
logging: :logging { class: module-Multiplatform }
test_di: :test:di { class: module-DI }
budget_data -> budget_model { class: link-api }
budget_data -> core_model { class: link-api }
budget_data -> logging { class: link-implementation }
core_di -> budget_data { class: link-api }
core_di -> budget_model { class: link-api }
test_di -> core_di { class: link-api }
vars: {
  d2-legend: {
    module-Multiplatform: Multiplatform { class: module-Multiplatform }
    module-DI: DI { class: module-DI }
    module-dummy1.class: hidden
    module-dummy2.class: hidden
    module-dummy1 -> module-dummy2: api { class: link-api }
    module-dummy1 -> module-dummy2: implementation { class: link-implementation }
  }
}
