package aktual.core.theme

import aktual.test.ThemeResponses
import androidx.compose.ui.graphics.Color
import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test

private val C = Color(0x00000000L)

class ParseThemeTest {
  @Test
  fun `Parse CSS as theme`() {
    assertThat(parseTheme(ThemeResponses.ACTUAL_200)).isEqualTo(
        CustomTheme(
            page =
                PageColors(
                    pageBackground = C,
                    pageBackgroundModalActive = C,
                    pageBackgroundTopLeft = C,
                    pageBackgroundBottomRight = C,
                    pageBackgroundLineTop = C,
                    pageBackgroundLineMid = C,
                    pageBackgroundLineBottom = C,
                    pageText = C,
                    pageTextLight = C,
                    pageTextSubdued = C,
                    pageTextDark = C,
                    pageTextPositive = C,
                    pageTextLink = C,
                    pageTextLinkLight = C,
                    numberPositive = C,
                    numberNegative = C,
                    numberNeutral = C,
                    cardBackground = C,
                    cardBorder = C,
                    cardShadow = C,
                ),
            table =
                TableColors(
                    tableBackground = C,
                    tableRowBackgroundHover = C,
                    tableText = C,
                    tableTextLight = C,
                    tableTextSubdued = C,
                    tableTextSelected = C,
                    tableTextHover = C,
                    tableTextInactive = C,
                    tableHeaderText = C,
                    tableHeaderBackground = C,
                    tableBorder = C,
                    tableBorderSelected = C,
                    tableBorderHover = C,
                    tableBorderSeparator = C,
                    tableRowBackgroundHighlight = C,
                    tableRowBackgroundHighlightText = C,
                    tableRowHeaderBackground = C,
                    tableRowHeaderText = C,
                ),
            navigation =
                NavigationColors(
                    sidebarBackground = C,
                    sidebarItemBackgroundPositive = C,
                    sidebarItemBackgroundFailed = C,
                    sidebarItemAccentSelected = C,
                    sidebarItemBackgroundHover = C,
                    sidebarItemText = C,
                    sidebarItemTextSelected = C,
                    menuBackground = C,
                    menuItemBackground = C,
                    menuItemBackgroundHover = C,
                    menuItemText = C,
                    menuItemTextHover = C,
                    menuItemTextSelected = C,
                    menuItemTextHeader = C,
                    menuBorder = C,
                    menuBorderHover = C,
                    menuKeybindingText = C,
                    menuAutoCompleteBackground = C,
                    menuAutoCompleteBackgroundHover = C,
                    menuAutoCompleteText = C,
                    menuAutoCompleteTextHeader = C,
                ),
            modalMobile =
                ModalMobileColors(
                    modalBackground = C,
                    modalBorder = C,
                    mobileHeaderBackground = C,
                    mobileHeaderBackgroundSubdued = C,
                    mobileHeaderText = C,
                    mobileHeaderTextTransparent = C,
                    mobileHeaderTextSubdued = C,
                    mobileHeaderTextHover = C,
                    mobilePageBackground = C,
                    mobileNavBackground = C,
                    mobileNavItem = C,
                    mobileNavItemSelected = C,
                    mobileAccountShadow = C,
                    mobileAccountText = C,
                    mobileModalBackground = C,
                    mobileModalText = C,
                    mobileViewTheme = C,
                    mobileConfigServerViewTheme = C,
                    markdownNormal = C,
                    markdownDark = C,
                    markdownLight = C,
                ),
            button =
                ButtonColors(
                    buttonMenuText = C,
                    buttonMenuTextHover = C,
                    buttonMenuBackground = C,
                    buttonMenuBackgroundHover = C,
                    buttonMenuBorder = C,
                    buttonMenuSelectedText = C,
                    buttonMenuSelectedTextHover = C,
                    buttonMenuSelectedBackground = C,
                    buttonMenuSelectedBackgroundHover = C,
                    buttonMenuSelectedBorder = C,
                    buttonPrimaryText = C,
                    buttonPrimaryTextHover = C,
                    buttonPrimaryBackground = C,
                    buttonPrimaryBackgroundHover = C,
                    buttonPrimaryBorder = C,
                    buttonPrimaryShadow = C,
                    buttonPrimaryDisabledText = C,
                    buttonPrimaryDisabledBackground = C,
                    buttonPrimaryDisabledBorder = C,
                    buttonNormalText = C,
                    buttonNormalTextHover = C,
                    buttonNormalBackground = C,
                    buttonNormalBackgroundHover = C,
                    buttonNormalBorder = C,
                    buttonNormalShadow = C,
                    buttonNormalSelectedText = C,
                    buttonNormalSelectedBackground = C,
                    buttonNormalDisabledText = C,
                    buttonNormalDisabledBackground = C,
                    buttonNormalDisabledBorder = C,
                    calendarText = C,
                    calendarBackground = C,
                    calendarItemText = C,
                    calendarItemBackground = C,
                    calendarSelectedBackground = C,
                    calendarCellBackground = C,
                    buttonBareText = C,
                    buttonBareTextHover = C,
                    buttonBareBackground = C,
                    buttonBareBackgroundHover = C,
                    buttonBareBackgroundActive = C,
                    buttonBareDisabledText = C,
                    buttonBareDisabledBackground = C,
                ),
            status =
                StatusColors(
                    noticeBackground = C,
                    noticeBackgroundLight = C,
                    noticeBackgroundDark = C,
                    noticeText = C,
                    noticeTextLight = C,
                    noticeTextDark = C,
                    noticeTextMenu = C,
                    noticeBorder = C,
                    warningBackground = C,
                    warningText = C,
                    warningTextLight = C,
                    warningTextDark = C,
                    warningBorder = C,
                    errorBackground = C,
                    errorText = C,
                    errorTextDark = C,
                    errorTextDarker = C,
                    errorTextMenu = C,
                    errorBorder = C,
                    upcomingBackground = C,
                    upcomingText = C,
                    upcomingBorder = C,
                    successText = C,
                ),
            form =
                FormColors(
                    formLabelText = C,
                    formLabelBackground = C,
                    formInputBackground = C,
                    formInputBackgroundSelected = C,
                    formInputBackgroundSelection = C,
                    formInputBorder = C,
                    formInputTextReadOnlySelection = C,
                    formInputBorderSelected = C,
                    formInputText = C,
                    formInputTextSelected = C,
                    formInputTextPlaceholder = C,
                    formInputTextPlaceholderSelected = C,
                    formInputTextSelection = C,
                    formInputShadowSelected = C,
                    formInputTextHighlight = C,
                    checkboxText = C,
                    checkboxBackgroundSelected = C,
                    checkboxBorderSelected = C,
                    checkboxShadowSelected = C,
                    checkboxToggleBackground = C,
                    checkboxToggleBackgroundSelected = C,
                    checkboxToggleDisabled = C,
                ),
            misc =
                MiscColors(
                    pillBackground = C,
                    pillBackgroundLight = C,
                    pillText = C,
                    pillTextHighlighted = C,
                    pillBorder = C,
                    pillBorderDark = C,
                    pillBackgroundSelected = C,
                    pillTextSelected = C,
                    pillBorderSelected = C,
                    reportsRed = C,
                    reportsBlue = C,
                    reportsGreen = C,
                    reportsGray = C,
                    reportsLabel = C,
                    reportsInnerLabel = C,
                    reportsNumberPositive = C,
                    reportsNumberNegative = C,
                    reportsNumberNeutral = C,
                    reportsChartFill = C,
                    scrollbar = C,
                    scrollbarSelected = C,
                    sliderThumb = C,
                    sliderActiveTrack = C,
                    sliderActiveTick = C,
                    sliderInactiveTrack = C,
                    sliderInactiveTick = C,
                    dialogBackground = C,
                    dialogProgressWheelTrack = C,
                    budgetItemBackground = C,
                    budgetItemTextPrimary = C,
                    budgetItemTextSecondary = C,
                ),
        )
    )
  }
}
