direction: down
style: {
  fill: "#00000A"
}
vars: {
  d2-config: {
    center: true
    layout-engine: elk
    pad: 3
    sketch: false
    theme-id: 201
  }
}
classes: {
  project-ViewModel {
    style.fill: "#914141"
  }
  project-DI {
    style.fill: "#a17103"
  }
  project-UI {
    style.fill: "#6b6b01"
  }
  project-Kotlin {
    style.fill: "#160185"
  }
  project-App {
    style.fill: "#7a0101"
  }
  project-JVM {
    style.fill: "#2f015c"
  }
  project-Other {
    style.fill: "#808080"
  }
  link-commonMainApi {
  }
  link-commonMainImplementation {
    style.stroke: "aqua"
    style.stroke-dash: "4"
  }
  container {
  }
  hidden {
    style.opacity: 0
  }
}
(** -> **)[*].target-arrowhead.shape: arrow
(** -> **)[*].target-arrowhead.style.filled: true
***.style.font-size: 25
