direction: down
style: {
  fill: "transparent"
}
vars: {
  d2-config: {
    center: true
    dark-theme-id: 200
    layout-engine: elk
    pad: 5
    sketch: true
    theme-id: 102
  }
}
classes: {
  module-ViewModel {
    style.fill: "#F5A6A6"
  }
  module-DI {
    style.fill: "#FCB103"
  }
  module-UI {
    style.fill: "#FFFF55"
  }
  module-Android {
    style.fill: "#55FF55"
  }
  module-Multiplatform {
    style.fill: "#9D8DF1"
  }
  module-App {
    style.fill: "#FF5555"
  }
  module-JVM {
    style.fill: "#8000FF"
  }
  module-Other {
    style.fill: "#808080"
  }
  link-api {
    style.stroke-width: "3"
  }
  link-implementation {
    style.animated: "true"
    style.stroke-dash: "4"
  }
  container {
  }
  hidden {
    style.opacity: 0
  }
}
(** -> **)[*].target-arrowhead.shape: arrow
(** -> **)[*].target-arrowhead.style.filled: true
