package aktual.budget.model

import aktual.budget.model.CurrencySymbolPosition.AfterAmount
import aktual.budget.model.CurrencySymbolPosition.BeforeAmount
import aktual.budget.model.NumberFormat.ApostropheDot
import aktual.budget.model.NumberFormat.CommaDot
import aktual.budget.model.NumberFormat.CommaDotIn
import aktual.budget.model.NumberFormat.DotComma
import aktual.budget.model.NumberFormat.SpaceComma
import androidx.compose.runtime.Immutable

enum class Currency(
  val code: String,
  val symbol: String,
  val decimalPlaces: Int,
  val numberFormat: NumberFormat,
  val symbolPosition: CurrencySymbolPosition,
) {
  None(
    code = "",
    symbol = "",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  UaeDirham(
    code = "AED",
    symbol = "د.إ",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = AfterAmount,
  ),
  ArgentinianPeso(
    code = "ARS",
    symbol = "Arg$",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = BeforeAmount,
  ),
  AustralianDollar(
    code = "AUD",
    symbol = "A$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  BrazilianReal(
    code = "BRL",
    symbol = "R$",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = BeforeAmount,
  ),
  BelarusianRuble(
    code = "BYN",
    symbol = "Br",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  CanadianDollar(
    code = "CAD",
    symbol = "CA$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  SwissFranc(
    code = "CHF",
    symbol = "Fr.",
    decimalPlaces = 2,
    numberFormat = ApostropheDot,
    symbolPosition = BeforeAmount,
  ),
  YuanRenminbi(
    code = "CNY",
    symbol = "¥",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  ColombianPeso(
    code = "COP",
    symbol = "Col$",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = BeforeAmount,
  ),
  CostaRicanColon(
    code = "CRC",
    symbol = "₡",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = BeforeAmount,
  ),
  CzechKoruna(
    code = "CZK",
    symbol = "Kč",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  DanishKrone(
    code = "DKK",
    symbol = "kr",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
  EgyptianPound(
    code = "EGP",
    symbol = "ج.م",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = AfterAmount,
  ),
  Euro(
    code = "EUR",
    symbol = "€",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
  PoundSterling(
    code = "GBP",
    symbol = "£",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  GuatemalanQuetzal(
    code = "GTQ",
    symbol = "Q",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  HongKongDollar(
    code = "HKD",
    symbol = "HK$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  HungarianForint(
    code = "HUF",
    symbol = "Ft",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  IndonesianRupiah(
    code = "IDR",
    symbol = "Rp",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = BeforeAmount,
  ),
  IndianRupee(
    code = "INR",
    symbol = "₹",
    decimalPlaces = 2,
    numberFormat = CommaDotIn,
    symbolPosition = BeforeAmount,
  ),
  JamaicanDollar(
    code = "JMD",
    symbol = "J$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  JapaneseYen(
    code = "JPY",
    symbol = "¥",
    decimalPlaces = 0,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  SouthKoreanWon(
    code = "KRW",
    symbol = "₩",
    decimalPlaces = 0,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  SriLankanRupee(
    code = "LKR",
    symbol = "Rs.",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  MoldovanLeu(
    code = "MDL",
    symbol = "L",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
  MalaysianRinggit(
    code = "MYR",
    symbol = "RM",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  PhilippinePeso(
    code = "PHP",
    symbol = "₱",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  PolishZloty(
    code = "PLN",
    symbol = "zł",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  QatariRiyal(
    code = "QAR",
    symbol = "ر.ق",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = AfterAmount,
  ),
  RomanianLeu(
    code = "RON",
    symbol = "lei",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
  SerbianDinar(
    code = "RSD",
    symbol = "дин",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
  RussianRuble(
    code = "RUB",
    symbol = "₽",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  SaudiRiyal(
    code = "SAR",
    symbol = "ر.س",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = AfterAmount,
  ),
  SwedishKrona(
    code = "SEK",
    symbol = "kr",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  SingaporeDollar(
    code = "SGD",
    symbol = "S$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  ThaiBaht(
    code = "THB",
    symbol = "฿",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  TurkishLira(
    code = "TRY",
    symbol = "₺",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = BeforeAmount,
  ),
  UkrainianHryvnia(
    code = "UAH",
    symbol = "₴",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  UsDollar(
    code = "USD",
    symbol = "$",
    decimalPlaces = 2,
    numberFormat = CommaDot,
    symbolPosition = BeforeAmount,
  ),
  UzbekSoum(
    code = "UZS",
    symbol = "UZS",
    decimalPlaces = 2,
    numberFormat = SpaceComma,
    symbolPosition = AfterAmount,
  ),
  VietnameseDong(
    code = "VND",
    symbol = "₫",
    decimalPlaces = 2,
    numberFormat = DotComma,
    symbolPosition = AfterAmount,
  ),
}

enum class CurrencySymbolPosition {
  BeforeAmount,
  AfterAmount,
}

@Immutable
data class CurrencyConfig(
  val currency: Currency,
  val position: CurrencySymbolPosition,
  val includeSpace: Boolean,
)
